import { CPHikeContextProvider } from "@/context/CPHikeContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "CP Hike",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <CPHikeContextProvider>{children}</CPHikeContextProvider>
    </div>
  );
}
